version: '3.8'

services:
  # Development service
  app-dev:
    build:
      context: .
      target: build
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development
    profiles:
      - dev

  # Production service (optimized for Lovable.dev)
  app:
    build: .
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
    restart: unless-stopped
    profiles:
      - prod

  # Alternative development service with hot reload
  dev:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
    profiles:
      - dev-hot